var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/Documents_GitHub_pana-web_16a503af._.js")
R.c("server/chunks/ssr/Documents_GitHub_pana-web_4ffd2e27._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ecf09555._.js")
R.c("server/chunks/ssr/51a83_next_dist_ff3c1520._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f33b4abe._.js")
R.c("server/chunks/ssr/[root-of-the-server]__712a335e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__71f49b88._.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_builtin_global-error_4ea635ea.js")
R.c("server/chunks/ssr/[root-of-the-server]__ee2e3bb4._.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_35e4d45f._.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_builtin_forbidden_bfa8ba3a.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_builtin_unauthorized_a066e4b5.js")
R.c("server/chunks/ssr/Documents_GitHub_pana-web__next-internal_server_app_page_actions_92644755.js")
R.m(32883)
module.exports=R.m(32883).exports
