var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about/page.js")
R.c("server/chunks/ssr/Documents_GitHub_pana-web_b82bd527._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ecf09555._.js")
R.c("server/chunks/ssr/Documents_GitHub_pana-web_87baa465._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f33b4abe._.js")
R.c("server/chunks/ssr/[root-of-the-server]__712a335e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__71f49b88._.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_builtin_global-error_4ea635ea.js")
R.c("server/chunks/ssr/[root-of-the-server]__ee2e3bb4._.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_35e4d45f._.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_builtin_forbidden_bfa8ba3a.js")
R.c("server/chunks/ssr/51a83_next_dist_client_components_builtin_unauthorized_a066e4b5.js")
R.c("server/chunks/ssr/Documents_GitHub_pana-web__next-internal_server_app_about_page_actions_4b00bb15.js")
R.m(15925)
module.exports=R.m(15925).exports
