module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/components/services/ui/ServiceLayout.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/services/ui/ServiceLayout.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/services/ui/ServiceLayout.tsx <module evaluation>", "default");
}),
"[project]/components/services/ui/ServiceLayout.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/components/services/ui/ServiceLayout.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/components/services/ui/ServiceLayout.tsx", "default");
}),
"[project]/components/services/ui/ServiceLayout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$services$2f$ui$2f$ServiceLayout$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/components/services/ui/ServiceLayout.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$services$2f$ui$2f$ServiceLayout$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/components/services/ui/ServiceLayout.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$services$2f$ui$2f$ServiceLayout$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/lib/services-data.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "services",
    ()=>services
]);
const services = [
    {
        slug: 'digital-print',
        title: 'Digital Paper Print Solutions',
        subtitle: 'Precision printing that elevates your brand.',
        description: '<p>Bring ideas to life with production-grade digital printing built for clarity, speed, and consistency. From business cards and brochures to reports and marketing kits, we deliver polished results that represent your brand at its best.</p>' + '<p>Expect ultrafine detail, color-accurate output, and flexible finishing — all handled in-house for reliable quality and quick turnaround.</p>',
        features: [
            'Ultrafine 1200 DPI detail',
            'Color-accurate CMYK + Pantone support',
            'Same-day and rush options',
            'Premium papers and finishes',
            'In-house binding, lamination, and kitting'
        ],
        equipment: 'Konica Minolta AccurioPress series, Duplo binders, cold/hot laminators',
        images: [
            {
                src: '/digitalpaperprint.jpg',
                alt: 'Accordion brochure mockup on concrete surface'
            },
            {
                src: '/sample-2.jpg',
                alt: 'Business card close-up'
            },
            {
                src: '/sample-3.jpeg',
                alt: 'Magazine spread'
            },
            {
                src: '/sample-4.png',
                alt: 'Event posters'
            }
        ],
        options: {
            sizes: [
                'A3',
                'A4',
                'A5',
                'Letter',
                'Custom'
            ],
            materials: [
                'Matte 150gsm',
                'Gloss 200gsm',
                'Textured 250gsm',
                'Cardstock 300gsm'
            ],
            finishes: [
                'None',
                'Matte Lamination',
                'Gloss Lamination',
                'UV Spot',
                'Foil'
            ],
            colors: [
                'Full Color',
                'Black & White',
                'Pantone'
            ],
            sides: [
                'Single-Sided',
                'Double-Sided'
            ]
        },
        basePrice: 0.5
    },
    {
        slug: 'signage',
        title: 'Indoor & Outdoor Signage',
        subtitle: 'Make a statement that lasts.',
        description: '<p>Command attention with signage engineered for impact and durability. Whether storefronts, wayfinding, or large-scale promotional displays, we craft solutions that are bold, legible, and built to withstand the elements.</p>' + '<p>From illumination to precision-cut lettering, every piece is produced and finished to professional standards.</p>',
        features: [
            'Illuminated and non-illuminated options',
            'CNC / laser-cut letters and shapes',
            'Weatherproof, long-lasting materials',
            'Professional installation'
        ],
        images: [
            {
                src: '/indoorsinage.jpg',
                alt: 'Emergency exit sign on yellow brick wall'
            },
            {
                src: '/outdoorsinage.jpg',
                alt: 'Outdoor signage installation with bold branding'
            },
            {
                src: '/sample-3.jpeg',
                alt: 'Promotional signage wall'
            }
        ],
        options: {
            sizes: [
                'S',
                'M',
                'L',
                'XL',
                'Custom'
            ],
            materials: [
                'Acrylic',
                'Aluminum',
                'PVC',
                'Vinyl'
            ],
            finishes: [
                'Matte',
                'Gloss',
                'Anti-glare'
            ],
            colors: [
                'Full Color',
                'Spot Color'
            ],
            sides: [
                'Single-Sided',
                'Double-Sided'
            ]
        },
        basePrice: 2.0
    },
    {
        slug: 'flex-banner',
        title: 'Flex Banners',
        subtitle: 'Big, bold, and built to perform.',
        description: '<p>High-visibility flex banners designed for outdoor campaigns, events, and retail activations. Vivid color, reinforced edges, and reliable hardware make setup simple and performance dependable.</p>' + '<p>Scale up your message with large-format capabilities and durable materials that stand up to real-world use.</p>',
        features: [
            'UV-stable inks',
            'Reinforced hems & eyelets',
            'Large-format up to 3.2m width'
        ],
        images: [
            {
                src: '/flexbanner.jpg',
                alt: 'Flex banner production on large-format printer'
            },
            {
                src: '/sample-2.jpg',
                alt: 'Event banner with crowd'
            }
        ],
        options: {
            sizes: [
                '2x3m',
                '3x5m',
                'Custom'
            ],
            materials: [
                'Flex',
                'Mesh Flex'
            ],
            finishes: [
                'None',
                'Matte',
                'Gloss'
            ],
            colors: [
                'Full Color'
            ],
            sides: [
                'Single-Sided'
            ]
        },
        basePrice: 3.5
    },
    {
        slug: 'vinyl',
        title: 'Vinyl Printing & Cutting',
        subtitle: 'Turn surfaces into brand moments.',
        description: '<p>From vehicles to windows and walls, vinyl branding delivers high-impact visuals with precision-cut details and long-lasting adhesion.</p>' + '<p>Perfect for wraps, decals, and custom cutouts — all produced for durability and clean installation.</p>',
        features: [
            'Precision plotter cutting',
            'High-tack, long-life adhesives',
            'Vehicle, window, and wall applications'
        ],
        images: [
            {
                src: '/vinlyprinting.png',
                alt: 'Modern green exhibition panels with silver frame'
            },
            {
                src: '/sample-2.jpg',
                alt: 'Window graphics on storefront'
            }
        ],
        options: {
            sizes: [
                'S',
                'M',
                'L',
                'Custom'
            ],
            materials: [
                'Gloss Vinyl',
                'Matte Vinyl',
                'Clear Vinyl'
            ],
            finishes: [
                'None',
                'Laminate'
            ],
            colors: [
                'Full Color',
                'Spot Color'
            ],
            sides: [
                'Single-Sided'
            ]
        },
        basePrice: 1.2
    },
    {
        slug: 'fabric',
        title: 'Fabric Printing',
        subtitle: 'Soft signage that moves with your audience.',
        description: '<p>Premium fabric graphics with rich, dye-sublimated color for flags, tension frames, and event backdrops. Lightweight, wrinkle-resistant, and easy to transport.</p>' + '<p>Ideal for indoor environments and outdoor setups where texture and elegance matter.</p>',
        features: [
            'Dye-sublimation printing',
            'Wrinkle-resistant, soft-touch output',
            'Portable and event-ready'
        ],
        images: [
            {
                src: '/sample-3.jpeg',
                alt: 'Fabric tension display'
            },
            {
                src: '/sample-1.jpg',
                alt: 'Flags at an event'
            }
        ],
        options: {
            sizes: [
                'S',
                'M',
                'L',
                'Custom'
            ],
            materials: [
                'Poly Fabric',
                'Mesh Fabric'
            ],
            finishes: [
                'None',
                'Hem',
                'Grommets'
            ],
            colors: [
                'Full Color'
            ],
            sides: [
                'Single-Sided',
                'Double-Sided'
            ]
        },
        basePrice: 2.5
    },
    {
        slug: 'promotional',
        title: 'Promotional Merchandise',
        subtitle: 'Merch people actually keep.',
        description: '<p>Amplify brand recall with high-quality promotional items for campaigns, launches, and events. From apparel and drinkware to stationery and gifts, we curate and brand products that feel premium and purposeful.</p>',
        features: [
            'Wide product range',
            'Heat transfer, screen print, embroidery',
            'Bulk-friendly pricing'
        ],
        images: [
            {
                src: '/sample-5.png',
                alt: 'Promo items assortment'
            },
            {
                src: '/sample-2.jpg',
                alt: 'Branded tote bags'
            }
        ],
        options: {
            sizes: [
                'S',
                'M',
                'L',
                'Custom'
            ],
            materials: [
                'Plastic',
                'Cotton',
                'Metal'
            ],
            finishes: [
                'None',
                'Gloss',
                'Matte'
            ],
            colors: [
                'Full Color',
                'One Color'
            ],
            sides: [
                'Single-Sided'
            ]
        },
        basePrice: 0.8
    },
    {
        slug: 'design',
        title: 'Creative Design Services',
        subtitle: 'From strategy to pixel-perfect execution.',
        description: '<p>Partner with a creative team that aligns design to outcomes. We develop brand identities, campaign visuals, and production-ready assets that look great and work hard across print and digital.</p>',
        features: [
            'Logo & identity systems',
            'Campaign and marketing visuals',
            'Print-ready and digital templates'
        ],
        images: [
            {
                src: '/graphicdesign.jpg',
                alt: 'Graphic design mockup signage'
            },
            {
                src: '/sample-3.jpeg',
                alt: 'Layout design preview'
            }
        ],
        options: {
            services: [
                'Logo',
                'Brand Kit',
                'Poster Design',
                'Social Templates'
            ]
        },
        basePrice: 5.0
    },
    {
        slug: 'events',
        title: 'Event Branding & Production',
        subtitle: 'End-to-end branding and on-site support.',
        description: '<p>Make events memorable with cohesive branding, signage, and production support. From concept to execution, we handle booths, backdrops, directional systems, and attendee materials for a seamless experience.</p>',
        features: [
            'Booths & stands',
            'Backdrops & stages',
            'Directional signage',
            'Attendee kits',
            'On-site production support'
        ],
        images: [
            {
                src: '/sample-2.jpg',
                alt: 'Event booth branding'
            },
            {
                src: '/sample-3.jpeg',
                alt: 'Venue signage'
            }
        ],
        options: {
            packages: [
                'Basic',
                'Standard',
                'Premium'
            ]
        },
        basePrice: 4.0
    }
];
}),
"[project]/app/services/[slug]/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>ServicePage,
    "generateMetadata",
    ()=>generateMetadata,
    "generateStaticParams",
    ()=>generateStaticParams
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$api$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/next/dist/api/navigation.react-server.js [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$components$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/components/navigation.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$components$2f$services$2f$ui$2f$ServiceLayout$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/components/services/ui/ServiceLayout.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/lib/services-data.ts [app-rsc] (ecmascript)");
;
;
;
;
async function generateStaticParams() {
    return __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["services"].map((s)=>({
            slug: s.slug
        }));
}
async function generateMetadata({ params }) {
    const { slug } = await params;
    const normalized = decodeURIComponent(slug).replace(/^\/+|\/+$/g, "");
    const service = __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["services"].find((s)=>s.slug === normalized);
    if (!service) {
        return {
            title: `Services | PANA`,
            description: "Explore print, signage, events, and design services."
        };
    }
    return {
        title: `${service.title} | PANA`,
        description: service.subtitle ?? service.description?.replace(/<[^>]*>?/gm, "").slice(0, 160),
        openGraph: {
            title: `${service.title} | PANA`,
            description: service.subtitle ?? undefined,
            images: service.images?.length ? [
                {
                    url: service.images[0].src
                }
            ] : undefined
        }
    };
}
async function ServicePage({ params }) {
    const { slug } = await params;
    const normalized = decodeURIComponent(slug).replace(/^\/+|\/+$/g, "");
    const service = __TURBOPACK__imported__module__$5b$project$5d2f$lib$2f$services$2d$data$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["services"].find((s)=>s.slug === normalized);
    if (!service) return (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$components$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["notFound"])();
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$components$2f$services$2f$ui$2f$ServiceLayout$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
        service: service
    }, void 0, false, {
        fileName: "[project]/app/services/[slug]/page.tsx",
        lineNumber: 38,
        columnNumber: 10
    }, this);
}
}),
"[project]/app/services/[slug]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/services/[slug]/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__50701a4f._.js.map