import { ServiceSpec } from '@/types/service';

export const services: ServiceSpec[] = [
  {
    slug: 'digital-print',
    title: 'Digital Paper Print Solutions',
    subtitle: 'Vivid. Crisp. Fast. Your message, perfectly printed.',
    description: 'We deliver high-quality printing for brochures, flyers, business cards, posters, booklets, magazines, labels, stickers, calendars, and more. 1200 DPI clarity, vibrant CMYK colors, and same-day turnaround on most jobs.',
    features: [
      '1200 DPI precision',
      'Full CMYK + Pantone matching',
      'Same-day rush available',
      'Eco paper options',
      'In-house binding & lamination',
    ],
    equipment: 'Konica Minolta AccurioPress, Industrial Binders, Roll Laminators',
    images: [
      { src: '/sample-1.jpg', alt: 'Brochure stack with vibrant colors' },
      { src: '/sample-2.jpg', alt: 'Business card close-up' },
      { src: '/sample-3.jpeg', alt: 'Magazine spread' },
      { src: '/sample-4.png', alt: 'Event posters' },
    ],
    options: {
      sizes: ['A3', 'A4', 'A5', 'Letter', 'Custom'],
      materials: ['Matte 150gsm', 'Gloss 200gsm', 'Textured 250gsm', 'Cardstock 300gsm'],
      finishes: ['None', 'Matte Lamination', 'Gloss Lamination', 'UV Spot', 'Foil'],
      colors: ['Full Color', 'Black & White', 'Pantone'],
      sides: ['Single-Sided', 'Double-Sided'],
    },
    basePrice: 0.5,
  },
  {
    slug: 'signage',
    title: 'Indoor & Outdoor Signage',
    subtitle: 'Durable, high-impact signs for storefronts, venues, and campaigns.',
    description: 'Signs engineered to endure and impress. From storefronts to wayfinding, fabricated for clarity and brand impact.',
    features: ['Weather-resistant materials', 'Vivid UV inks', 'Custom shapes & sizes', 'Professional installation'],
    images: [
      { src: '/sample-2.jpg', alt: 'Storefront signage with bold branding' },
      { src: '/sample-5.png', alt: 'Wayfinding signs in a venue' },
      { src: '/sample-3.jpeg', alt: 'Promotional signage wall' },
    ],
    options: {
      sizes: ['S', 'M', 'L', 'XL', 'Custom'],
      materials: ['Acrylic', 'Aluminum', 'PVC', 'Vinyl'],
      finishes: ['Matte', 'Gloss', 'Anti-glare'],
      colors: ['Full Color', 'Spot Color'],
      sides: ['Single-Sided', 'Double-Sided'],
    },
    basePrice: 2.0,
  },
  {
    slug: 'flex-banner',
    title: 'Flex Banners',
    subtitle: 'High-visibility banners for outdoor advertising and events.',
    description: 'Strong, vibrant banners built to last in the elements. Ideal for promotions and event branding.',
    features: ['Weather-resistant flex material', 'Reinforced hems & eyelets', 'Large-format printing'],
    images: [
      { src: '/sample-1.jpg', alt: 'Outdoor flex banner on building' },
      { src: '/sample-2.jpg', alt: 'Event banner with crowd' },
    ],
    options: {
      sizes: ['2x3m', '3x5m', 'Custom'],
      materials: ['Flex', 'Mesh Flex'],
      finishes: ['None', 'Matte', 'Gloss'],
      colors: ['Full Color'],
      sides: ['Single-Sided'],
    },
    basePrice: 3.5,
  },
  {
    slug: 'vinyl',
    title: 'Vinyl Printing & Cutting',
    subtitle: 'Decals, vehicle wraps, and window graphics that stick and shine.',
    description: 'Precision-cut vinyl with durable adhesives for long-lasting applications across vehicles, windows, and products.',
    features: ['Precision plotter cutting', 'High-tack adhesives', 'Outdoor-grade durability'],
    images: [
      { src: '/sample-4.png', alt: 'Vehicle wrap in progress' },
      { src: '/sample-2.jpg', alt: 'Window graphics on storefront' },
    ],
    options: {
      sizes: ['S', 'M', 'L', 'Custom'],
      materials: ['Gloss Vinyl', 'Matte Vinyl', 'Clear Vinyl'],
      finishes: ['None', 'Laminate'],
      colors: ['Full Color', 'Spot Color'],
      sides: ['Single-Sided'],
    },
    basePrice: 1.2,
  },
  {
    slug: 'fabric',
    title: 'Fabric Printing',
    subtitle: 'Soft signage, flags, and tension displays with premium fabric.',
    description: 'Lightweight, wrinkle-resistant fabric prints with rich color for indoor and outdoor setups.',
    features: ['Dye-sublimation printing', 'Wrinkle-resistant', 'Easy to transport'],
    images: [
      { src: '/sample-3.jpeg', alt: 'Fabric tension display' },
      { src: '/sample-1.jpg', alt: 'Flags at an event' },
    ],
    options: {
      sizes: ['S', 'M', 'L', 'Custom'],
      materials: ['Poly Fabric', 'Mesh Fabric'],
      finishes: ['None', 'Hem', 'Grommets'],
      colors: ['Full Color'],
      sides: ['Single-Sided', 'Double-Sided'],
    },
    basePrice: 2.5,
  },
  {
    slug: 'promotional',
    title: 'Promotional Merchandise',
    subtitle: 'Branded giveaways and merch that people keep and love.',
    description: 'High-quality promotional items for campaigns and events.',
    features: ['Wide range of products', 'Durable branding', 'Bulk pricing'],
    images: [
      { src: '/sample-5.png', alt: 'Promo items assortment' },
      { src: '/sample-2.jpg', alt: 'Branded tote bags' },
    ],
    options: {
      sizes: ['S', 'M', 'L', 'Custom'],
      materials: ['Plastic', 'Cotton', 'Metal'],
      finishes: ['None', 'Gloss', 'Matte'],
      colors: ['Full Color', 'One Color'],
      sides: ['Single-Sided'],
    },
    basePrice: 0.8,
  },
  {
    slug: 'design',
    title: 'Creative Design Services',
    subtitle: 'Brand identity, campaign concepts, and production-ready assets.',
    description: 'Compelling visuals aligned with your goals. Includes brand kits, layouts, and print-ready files.',
    features: ['Brand identity', 'Campaign design', 'Print-ready assets'],
    images: [
      { src: '/sample-1.jpg', alt: 'Design moodboard' },
      { src: '/sample-3.jpeg', alt: 'Layout design preview' },
    ],
    options: {
      services: ['Logo', 'Brand Kit', 'Poster Design', 'Social Templates'],
    },
    basePrice: 5.0,
  },
  {
    slug: 'events',
    title: 'Event Branding & Production',
    subtitle: 'End-to-end event branding, signage, and on-site support.',
    description: 'Make events memorable with cohesive branding, signage, and production support.',
    features: ['Booth branding', 'Directional signage', 'On-site support'],
    images: [
      { src: '/sample-2.jpg', alt: 'Event booth branding' },
      { src: '/sample-3.jpeg', alt: 'Venue signage' },
    ],
    options: {
      packages: ['Basic', 'Standard', 'Premium'],
    },
    basePrice: 4.0,
  },
];