// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/blog" | "/home" | "/services" | "/services/[slug]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/services/creative-design" | "/services/digital-paper-print-solutions" | "/services/event-services" | "/services/fabric-printing" | "/services/flex-banners" | "/services/indoor-outdoor-signage" | "/services/promotional-items" | "/services/vinyl-graphics"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/blog": {}
  "/home": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/services/creative-design": {}
  "/services/digital-paper-print-solutions": {}
  "/services/event-services": {}
  "/services/fabric-printing": {}
  "/services/flex-banners": {}
  "/services/indoor-outdoor-signage": {}
  "/services/promotional-items": {}
  "/services/vinyl-graphics": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
